sudo: required
services:
  - docker

before_install:
  - docker image build -t thpaggie910/docker-react -f Dockerfile.dev .

script:
  - docker container run thpaggie910/docker-react npm run test -- --coverage
